// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_datas.proto

package com.zzp.second.kill.admin.grpc.domain;

public final class GrpcMessage {
  private GrpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysUserTokenInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysUserTokenInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020grpc_datas.proto\"K\n\020SysUserTokenInfo\022\020" +
      "\n\010username\030\001 \001(\t\022\020\n\010passwrod\030\002 \001(\t\022\023\n\013au" +
      "thorities\030\003 \003(\tB6\n%com.zzp.second.kill.a" +
      "dmin.grpc.domainB\013GrpcMessageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SysUserTokenInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SysUserTokenInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysUserTokenInfo_descriptor,
        new java.lang.String[] { "Username", "Passwrod", "Authorities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
