// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_datas.proto

package com.zzp.second.kill.admin.grpc.domain;

public interface SysUserTokenInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SysUserTokenInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string passwrod = 2;</code>
   */
  java.lang.String getPasswrod();
  /**
   * <code>string passwrod = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswrodBytes();

  /**
   * <code>repeated string authorities = 3;</code>
   */
  java.util.List<java.lang.String>
      getAuthoritiesList();
  /**
   * <code>repeated string authorities = 3;</code>
   */
  int getAuthoritiesCount();
  /**
   * <code>repeated string authorities = 3;</code>
   */
  java.lang.String getAuthorities(int index);
  /**
   * <code>repeated string authorities = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthoritiesBytes(int index);
}
