// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_datas.proto

package com.zzp.second.kill.admin.grpc.domain;

/**
 * Protobuf type {@code SysUserTokenInfo}
 */
public  final class SysUserTokenInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SysUserTokenInfo)
    SysUserTokenInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SysUserTokenInfo.newBuilder() to construct.
  private SysUserTokenInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SysUserTokenInfo() {
    username_ = "";
    passwrod_ = "";
    authorities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SysUserTokenInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SysUserTokenInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            passwrod_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              authorities_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            authorities_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        authorities_ = authorities_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zzp.second.kill.admin.grpc.domain.GrpcMessage.internal_static_SysUserTokenInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zzp.second.kill.admin.grpc.domain.GrpcMessage.internal_static_SysUserTokenInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.class, com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 1;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWROD_FIELD_NUMBER = 2;
  private volatile java.lang.Object passwrod_;
  /**
   * <code>string passwrod = 2;</code>
   */
  public java.lang.String getPasswrod() {
    java.lang.Object ref = passwrod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passwrod_ = s;
      return s;
    }
  }
  /**
   * <code>string passwrod = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPasswrodBytes() {
    java.lang.Object ref = passwrod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passwrod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORITIES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList authorities_;
  /**
   * <code>repeated string authorities = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAuthoritiesList() {
    return authorities_;
  }
  /**
   * <code>repeated string authorities = 3;</code>
   */
  public int getAuthoritiesCount() {
    return authorities_.size();
  }
  /**
   * <code>repeated string authorities = 3;</code>
   */
  public java.lang.String getAuthorities(int index) {
    return authorities_.get(index);
  }
  /**
   * <code>repeated string authorities = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAuthoritiesBytes(int index) {
    return authorities_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (!getPasswrodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passwrod_);
    }
    for (int i = 0; i < authorities_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, authorities_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (!getPasswrodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passwrod_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < authorities_.size(); i++) {
        dataSize += computeStringSizeNoTag(authorities_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAuthoritiesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo)) {
      return super.equals(obj);
    }
    com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo other = (com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo) obj;

    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPasswrod()
        .equals(other.getPasswrod())) return false;
    if (!getAuthoritiesList()
        .equals(other.getAuthoritiesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWROD_FIELD_NUMBER;
    hash = (53 * hash) + getPasswrod().hashCode();
    if (getAuthoritiesCount() > 0) {
      hash = (37 * hash) + AUTHORITIES_FIELD_NUMBER;
      hash = (53 * hash) + getAuthoritiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SysUserTokenInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SysUserTokenInfo)
      com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzp.second.kill.admin.grpc.domain.GrpcMessage.internal_static_SysUserTokenInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzp.second.kill.admin.grpc.domain.GrpcMessage.internal_static_SysUserTokenInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.class, com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.Builder.class);
    }

    // Construct using com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";

      passwrod_ = "";

      authorities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zzp.second.kill.admin.grpc.domain.GrpcMessage.internal_static_SysUserTokenInfo_descriptor;
    }

    @java.lang.Override
    public com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo getDefaultInstanceForType() {
      return com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo build() {
      com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo buildPartial() {
      com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo result = new com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo(this);
      int from_bitField0_ = bitField0_;
      result.username_ = username_;
      result.passwrod_ = passwrod_;
      if (((bitField0_ & 0x00000001) != 0)) {
        authorities_ = authorities_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.authorities_ = authorities_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo) {
        return mergeFrom((com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo other) {
      if (other == com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPasswrod().isEmpty()) {
        passwrod_ = other.passwrod_;
        onChanged();
      }
      if (!other.authorities_.isEmpty()) {
        if (authorities_.isEmpty()) {
          authorities_ = other.authorities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAuthoritiesIsMutable();
          authorities_.addAll(other.authorities_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object passwrod_ = "";
    /**
     * <code>string passwrod = 2;</code>
     */
    public java.lang.String getPasswrod() {
      java.lang.Object ref = passwrod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passwrod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string passwrod = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswrodBytes() {
      java.lang.Object ref = passwrod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwrod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string passwrod = 2;</code>
     */
    public Builder setPasswrod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passwrod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string passwrod = 2;</code>
     */
    public Builder clearPasswrod() {
      
      passwrod_ = getDefaultInstance().getPasswrod();
      onChanged();
      return this;
    }
    /**
     * <code>string passwrod = 2;</code>
     */
    public Builder setPasswrodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passwrod_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList authorities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAuthoritiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        authorities_ = new com.google.protobuf.LazyStringArrayList(authorities_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAuthoritiesList() {
      return authorities_.getUnmodifiableView();
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public int getAuthoritiesCount() {
      return authorities_.size();
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public java.lang.String getAuthorities(int index) {
      return authorities_.get(index);
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAuthoritiesBytes(int index) {
      return authorities_.getByteString(index);
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public Builder setAuthorities(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthoritiesIsMutable();
      authorities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public Builder addAuthorities(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthoritiesIsMutable();
      authorities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public Builder addAllAuthorities(
        java.lang.Iterable<java.lang.String> values) {
      ensureAuthoritiesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, authorities_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public Builder clearAuthorities() {
      authorities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authorities = 3;</code>
     */
    public Builder addAuthoritiesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAuthoritiesIsMutable();
      authorities_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SysUserTokenInfo)
  }

  // @@protoc_insertion_point(class_scope:SysUserTokenInfo)
  private static final com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo();
  }

  public static com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SysUserTokenInfo>
      PARSER = new com.google.protobuf.AbstractParser<SysUserTokenInfo>() {
    @java.lang.Override
    public SysUserTokenInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SysUserTokenInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SysUserTokenInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SysUserTokenInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zzp.second.kill.admin.grpc.domain.SysUserTokenInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

